### ISSUE TITLE
Feature: Real Debrid support

### ISSUE THREAD

**Issue by Rmz23** [mhdzumair/tamilblasters_stremio_addon#1]
Your addon works great and it scraper really well, but could you provide Real Debrid support like torrentio
https://github.com/TheBeastLT/torrentio-scraper/

**Comment by mhdzumair** [comment]
Hi @Rmz23 thanks for reaching out. I'm not aware what is “Read Debrid Support”?

**Comment by mhdzumair** [comment]
> Hi @Rmz23 thanks for reaching out. I was checked their source code. That serve direct download option to torrent file [!Ref](https://github.com/TheBeastLT/torrentio-scraper/blob/master/addon/serverless.js#L72) .
> 
> Since I dont have server to host my add-on, this is not possible in stremio beamup server. Use stremio download option for now.

@KARANRSB thanks for bringing back this topic. My bad :disappointed: , I was not checked entire code. It seems like real-debrid is a third party premium service that provide high speed streaming for torrent (like seedr.cc). 

Unlike seedr, real-debrid doesn't provide free usage. I cant even develop and test the add-on.  I like the seedr for watching torrent filim, I'll create strory to integrate seedr. 

If someone is helping on creating real-debrid integration (funding for premium subscription :wink:), I'm happy to do that.

**Comment by Rmz23** [comment]
I am down to sponsor a real debrid account for you if you can work on this

**Comment by KARANRSB** [comment]
But how much time will u require if funding for premium subscription is
given and also once it's done how will it work?

**Comment by KARANRSB** [comment]
I understood about seedr but everyone uses real debrid so

**Comment by mhdzumair** [comment]
I created this add-on in my free time, so I'm not looking for funding at this time. However, if I were to integrate Real-Debrid, there are several security concerns that I would need to address. User data must be handled securely, and I'm not currently storing any user data. I'm storing movie data in a free MongoDB Atlas server (500 MB) and hosting the add-on in a free Beamup server (provided by Stremio).

 If I were a user, I wouldn't want to store any API keys in such an application. I'm happy to read your feedback on this issue.

Additionally, I don't see any option to create an OAuth app on the Real-Debrid website (maybe due to non-subscription), nor is their [documentation](https://api.real-debrid.com/#three_legged) about how to do so (to get a client_id).

**Comment by mhdzumair** [comment]
> Additionally, I don't see any option to create an OAuth app on the Real-Debrid website (maybe due to non-subscription), nor is their [documentation](https://api.real-debrid.com/#three_legged) about how to do so (to get a client_id).

@Rmz23 I saw you forked this repo to add real-debrid support. So you already have an app_id ?

**Comment by Nikhil1920** [comment]
for anyone looking for real debrid support for this addon or any other stremio torrents addon checkout animose app [playstore link](https://play.google.com/store/apps/details?id=com.byanr.mose) [website](https://animose.byanr.com) for ios users it supports stemio addons.

The debrid integration happens on the client side and your api keys do not go through animose on the app you can check the network activity it also has cast to kodi support

**Comment by mhdzumair** [comment]
Thanks for the info @Nikhil1920. It's all under your own responsibility.

**Comment by mhdzumair** [comment]
> If I were a user, I wouldn't want to store any API keys in such an application. 

I have come up with the idea to work with user data most secure way. I created the addon configuration page which will help to store the api key and user preferences. Then the site will encrypt the user data with the secret key stored in the backend on clicking addon installation button. 

This will create user specific encrypted string with installation link which will be like "stremio://{URL}/{encrypted data}/manifest.json". Once you installed the add-on, This encrypted data is stored in your stremio application but stremio also doesn't know whats in the encrypted data. **Also Im not stored any of the user data in the backend. Only i have a secret key which can use for encryption and decryption.** Other than that your data is in with stremio. Stremio will send this data to backend everytime its make the api call, therefore i can able to decrypt the key and handle the user data. 

This approach is secure then the current torrentio addon which storing user data as plain text. So you can see the user preferences in the configuration link. If attacker is monitoring your network then attacker can easily steal the api keys.

**Comment by mhdzumair** [comment]
![image](https://github.com/mhdzumair/tamilblasters_stremio_addon/assets/44891939/8aab26bb-0a35-412e-8ea0-8aba85faefbd)

Use authorization button to get the device code setup token. Or use a previously created token by this application.  

**Important:** Do not use the Real-Debrid API token. even if you past, it wont work.

**Comment by mhdzumair** [comment]
Thanks for all the contribution :+1:

**Comment by KARANRSB** [comment]
Im unable to watch real debrid stream it says stremio encountered an error
with the media.

**Comment by mhdzumair** [comment]
It seems the hosted add-on is not working as intended. I have tested only with the local environment. Ill check and fix the issue.

**Comment by KARANRSB** [comment]
Sure and also it's not taking the token code into the space sometimes it
accepts and sometimes it doesn't work.

**Comment by mhdzumair** [comment]
It was expected behaviour. When you click on the authorize button, then the input will be disabled. If this is the case. Then it is expected behaviour.

**Comment by mhdzumair** [comment]
@KARANRSB  test the changes now. it's working for me currently. But other issues can happen while taking time to download the torrent in real debrid.

**Comment by KARANRSB** [comment]
Oh it's working amazing now.
Thanks a lot mhdzumair I was waiting for this from a long time watching it
without taking the magnet link into real debrid was what I wanted from the
first and now u have done it.Wow amazing but I still haven't tested
download to debrid so I'll let u know if there is any issue there,
Thanks.

**Comment by Rmz23** [comment]
Great Work Zumair

After a lot of trial and error, finally got it to work. For some reason, when I tried installing from the link in the main page it was not catching the api key, it only works with the link you gave in the comments although both seems to be same link

**Comment by mhdzumair** [comment]
> it was not catching the api key,

@Rmz23 could you explain this?  

I have coded as not to show the api key once you installed the addon in stremio. So next time if you're clicking the configure button in stremio, The configuration page won't show your api code what was previously configured. It's for Security purpose. Unlike the behaviour in torrentio add-on.

**Comment by Rmz23** [comment]
What was happening to me was, I would go to configuration page, click on the authorize with real debrid button, copy the device code to real-debrid.com/device web page and login and add the device. It would show the device is added in the real debrid website, But nothing would happen in the configuration page, the token value will not update and I was not able to add the addon. But after a lot of tries, it worked, when I did it from the link you posted on this comments thread. Earlier, I was trying to install from your main page link, so that might have been the issue

**Comment by mhdzumair** [comment]
@Rmz23 thanks for info. Create an issue #33

**Comment by mhdzumair** [comment]
@KARANRSB no need to try that much. 😅😅. The issue is fixed. Create a new issue if there is any new issue

**Comment by KARANRSB** [comment]
Yeah it's working properly now guys use the link in netlify that works fine
or the one posted by the creator.
