### ISSUE TITLE
Title and Quality

### ISSUE THREAD

**Issue by DEFRO5** [mhdzumair/tamilblasters_stremio_addon#16]
Quality and title of the movies are not properly named. Its a complete mess and dono what is what.
![image](https://github.com/mhdzumair/tamilblasters_stremio_addon/assets/52076521/a11ede81-ec05-4db4-8371-17a211eee08e)

we want a format like this
![image](https://github.com/mhdzumair/tamilblasters_stremio_addon/assets/52076521/c5737a0e-de04-40bd-8527-5a31e044f998)

**Comment by mhdzumair** [comment]
how about this? 
![image](https://github.com/mhdzumair/tamilblasters_stremio_addon/assets/44891939/c29d951d-ab6a-43c7-b304-fbe95b314828)

**Comment by DEFRO5** [comment]
Looks cool. Thanks
