### ISSUE TITLE
Real debrid support 

### ISSUE THREAD

**Issue by KARANRSB** [mhdzumair/tamilblasters_stremio_addon#17]
I already saw that someone has already told in September to add it and u told u don't have the resources for real debrid support but I just thought I'll ask again since it's been a year and I just love tamilblasters with real debrid cause it's very fast and no need for downloading that time so and also if u can't manually do it please request torrentio creater to do it on your behalf it's a request from my side,
Thanks.

**Comment by mhdzumair** [comment]
Duplicate #1
