### ISSUE TITLE
Not a single video is playing for me

### ISSUE THREAD

**Issue by SaurabhKaperwan** [mhdzumair/tamilblasters_stremio_addon#25]
Try in many movies and series and not a single one is playing

**Comment by SaurabhKaperwan** [comment]
Only few are working but most of them are very slow

**Comment by SaurabhKaperwan** [comment]
Can you also add numbers of seeds

**Comment by mhdzumair** [comment]
> Try in many movies and series and not a single one is playing

I'm not responsible for any of the contents. This is just scraping and indexing Add-on. Please check with Tamil Blasters site.

> Can you also add feature to see numbers of seeds

This is not possible unless using a torrent client to parse meta info and connect with seeders to find the current seeder count. The add-on is not a torrent downloader. 

If you know any torrent meta parser based on magnet link, then I can implement this feature.
