### ISSUE TITLE
New Stremio Add-on Request for Live Channels

### ISSUE THREAD

**Issue by naveenland4** [mhdzumair/tamilblasters_stremio_addon#3]
Hello Bro,

All your Addon for Tamilyogi and TamilBlasters are mind-blowing.

If possible can you please create an Addon for the live channels using the below site?

https://netlivetv.xyz/

Note: They update their links for jiotv and zee5 every one day.

Thanks in Advance.

**Comment by mhdzumair** [comment]
Hi @naveenland4 this is great idea. I wonder if there any other sources as well? Like vijay tv, sun tv etc

**Comment by naveenland4** [comment]
as of now i dont foresee any website have them. Will keep you posted. You may either generate a .m3u file using github action or an addon using streamio. But addon for iptv in stremio is not that much user friendly. :-)

**Comment by mhdzumair** [comment]
I saw you worked on some m3u project. Can you contribute on that part?

**Comment by muwai1** [comment]
they stopped working https://netlivetv.xyz/
