### ISSUE TITLE
2.0 installation issues 

### ISSUE THREAD

**Issue by Mcjuly** [mhdzumair/tamilblasters_stremio_addon#30]
Hi , Thanks for Tamil Blasters addon , been using from day one , but sorry to say this 2.0 is Kind of mess, or may be has bug when we configure prior to installation 
1 RD integration not doing anything
2 
It give me options to select my language ie. Hindi, Dubbed , English etc... but this configuration is not doing anything. I mean No mater what you select or not select it only installs 'new movies'  all in one bunch.. not sure if you wanted this way , but I really appriciate if you do change back to old ways like v 1.5 where we can select what language we preffered and also in separate language section rather then all in one bunch,  Ibdo not speak or understand south languages so for me to find new  hindi movies is very annoying have to keep scrolling to find , I gave up after few scrolls 
Again , APPRICIATE your hard work . but please fix Or give us option to use V1.5 
Thanks

**Comment by mhdzumair** [comment]
Thanks for creating the issue. The add-on is behind the streamio hosting service. They have enabled the caching by default. The problem you're facing with configuration is due to caching. I'll fix that issue. 

What is the issue with Real-Debrid integration? Please explain that issue.

**Comment by Mcjuly** [comment]
Thanks ,for Reply .
Happy to know that you will be fixing the issue.
Regarding RD , after Putting Code , It dosent do anything , but I think I
do not required to do RD configuration as , Its registered already on
stremio wide ( i might be wrong)
Never mind RD . I am not to concerned about it.

But , Again , Love to see , individual sections of Hindi , Dubbed and
English,  Both Movies and Series.

Which I believe,  will be fixed on next update.  Cant wait to see that.

Thanks and Regards
