### ISSUE TITLE
Version 2.0 Realdebrid Issue

### ISSUE THREAD

**Issue by jrjaggari** [mhdzumair/tamilblasters_stremio_addon#35]
Installed version 2.0 and I am getting the following error, "API Exception occured, Please try again or Submit an issue in github repository tamilblasters_stremio_addon" when I try to play a video.

**Comment by mhdzumair** [comment]
Hi @jrjaggari  please test the addon from this link https://streamio-tamil-blasters.onrender.com so that I can view trace logs. also, note that this link is for testing only I will terminate this link once after test is complete. LMK when you're going to test

**Comment by jrjaggari** [comment]
Planning to test now

**Comment by mhdzumair** [comment]
Closing as done
