### ISSUE TITLE
TamilBlaster addon

### ISSUE THREAD

**Issue by nitzz204u** [mhdzumair/tamilblasters_stremio_addon#38]
The TamilBlaster addon isn't functioning on Android TV. Although it installed successfully, when I attempt to select a film, it displays a "No addons found." Could you please assist me in resolving this issue? Thank you for your help.

**Comment by mhdzumair** [comment]
Hi @nitzz204u join this group to follow-up with android TV testing https://t.me/tamilblasters_stremio_addon

**Comment by mhdzumair** [comment]
I was tested in an android TV emulator with stremio. The streams are perfectly working. 

![image](https://github.com/mhdzumair/tamilblasters_stremio_addon/assets/44891939/a62d09b0-b0cf-4595-85c4-56d91c1a0462)


I'm not sure what errors you're getting. Please Join the telegram group for testing https://t.me/tamilblasters_stremio_addon

**Comment by KARANRSB** [comment]
Don't select the movie from cinemata catalogue or tmdb catalogue select it
from tamilblasters movie catalogue in search and it will give you the
stream.
