### ISSUE TITLE
Android TV: series in tamilblasters shows error.

### ISSUE THREAD

**Issue by sadamshajahan** [mhdzumair/tamilblasters_stremio_addon#9]
For the tamilblasters, I see some contents that are available in the movies sections, but I couldn't find any content for the Tamil series. Both the library content and the stream are available on my Android mobile app, but not in the Google TV app. Any suggestions?

https://github.com/mhdzumair/tamilblasters_streamio_addon  - Is the URL that I can see.

**Comment by mhdzumair** [comment]
I don't have android TV to test the issue. Can you try to intercept the request URL? So I can provide a solution for it.

**Comment by sadamshajahan** [comment]
https://882b9915d0fe-stremio-tamilblasters.baby-beamup.club/ 

Do you mean this? This is the page it goes when I click the add-on link.

**Comment by sadamshajahan** [comment]
![image](https://user-images.githubusercontent.com/121405845/209749427-19e7a909-fb77-4b51-b9a8-23cf48677530.png)

**Comment by mhdzumair** [comment]
No, I mean; when you click on any series in the stremio app in android tv. then it will try to send a http request. It's not visible to you.  We can check that request URL trough tools like `wireshark`. If you're not familiar with that. Will leave this issue as it is until someone will help on this.

**Comment by mhdzumair** [comment]
Closing as no further information.
